apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-cifar-train-gpu"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: kubeflow/pytorch-cifar:1.0
              args: ["--profile", "train", "--cuda", "--batch-size", "128", "--epochs", "20"]
              resources: 
                limits:
                  nvidia.com/gpu: 1
